from __future__ import annotations

# Bookmark relationships
TAGGED_WITH = "TAGGED_WITH"
HAS_THEME = "HAS_THEME"
DISCUSSED_IN = "DISCUSSED_IN"
EVIDENCES = "EVIDENCES"
RELATES_TO = "RELATES_TO"
AUTHORED_BY = "AUTHORED_BY"
COVERS_PLAYER = "COVERS_PLAYER"
PUBLISHED_BY = "PUBLISHED_BY"

# Session relationships
COVERS = "COVERS"
PRODUCED = "PRODUCED"
GENERATED = "GENERATED"
REFERENCED = "REFERENCED"
CONTAINED = "CONTAINED"

# Person relationships
PRESENTED_IN = "PRESENTED_IN"
RAISED = "RAISED"
ASSIGNED = "ASSIGNED"
PROMOTED = "PROMOTED"
LOCKED = "LOCKED"
OWNS = "OWNS"

# Argument relationships
SUPPORTS = "SUPPORTS"
CHALLENGES = "CHALLENGES"
REFERENCES = "REFERENCES"
MADE_IN = "MADE_IN"
COUNTERED_BY = "COUNTERED_BY"

# Position relationships
LOCKED_IN = "LOCKED_IN"
HAS_ANTI_POSITION = "HAS_ANTI_POSITION"
BRIDGES_TO = "BRIDGES_TO"
MAPS_TO = "MAPS_TO"
TESTED_BY = "TESTED_BY"
REPLACED_BY = "REPLACED_BY"

# Arc relationships
FOLLOWS = "FOLLOWS"
HAS_STEELMAN = "HAS_STEELMAN"
HAS_POSITION = "HAS_POSITION"

# Topic relationships
CO_OCCURS_WITH = "CO_OCCURS_WITH"

# Evidence relationships
SOURCED_FROM = "SOURCED_FROM"
GENERATED_IN = "GENERATED_IN"
