apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-standalone
  namespace: valliance-graph
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: valliance-graph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
