apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: valliance-graph
  namespace: valliance-graph
  labels:
    app.kubernetes.io/part-of: valliance-graph
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - graph.valliance.dev
      secretName: valliance-graph-tls
  rules:
    - host: graph.valliance.dev
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
